export type Lang = "en" | "es";

export const content = {
  en: {
    nav: { thesis: "Thesis", market: "Market", model: "Model", team: "Team", contact: "Contact" },
    hero: {
      kicker: "Investor brief · Pre-Seed",
      eyebrow: "B2B Infrastructure Platform · B2B2C Experience Layer · Insurtech",
      titleA: "The AI operations layer",
      titleB: "for insurance services.",
      body: "A real-time coordination infrastructure replacing call centers, intermediaries, and legacy operators.",
      explore: "Explore the thesis",
      signal: "AI-native · Real-time · Usage-based",
    },
    problem: {
      label: "01 · The problem",
      title: "The insurance operations layer is broken.",
      lead: "The traditional insurance assistance model is fragmented, expensive, and heavily dependent on manual coordination.",
      body: "Weso replaces call centers, intermediaries, and legacy operators with a real-time coordination infrastructure that reduces costs, improves execution, and transforms assistance into a scalable fee-for-service model.",
      marketTitle: "What’s broken in today’s market",
      marketLead: "Behind every insurance policy exists a fragmented operational infrastructure built decades before real-time automation.",
      cards: [
        ["Broken financial incentives", "The system makes more money when it spends less on customer service."],
        ["Reliance on intermediaries", "There are too many operational layers between the insurer and the actual solution."],
        ["Loss of customer control", "Insurance companies outsource their customer experience to external third parties."],
        ["Outdated infrastructure", "The current model still relies on manual processes and structures designed before the AI era."],
      ],
    },
    solution: {
      label: "02 · The solution",
      title: "Our solution, reimagined.",
      flow: ["Request", "AI Intake", "Match", "Dispatch", "Follow Up", "Resolution", "Data Back"],
      pillars: [
        ["One AI Operations Layer", "Weso consolidates TPAs, assistance companies, dispatch operations, and call centers into a single AI-powered coordination platform."],
        ["AI-native, real-time operations", "We automate service orchestration end-to-end with AI, reducing operational friction, response times, and fixed costs."],
        ["Usage-based economics", "Unlike legacy per-capita models, Weso operates with a flexible pay-per-use structure enabled by automation and intelligent coordination."],
      ],
    },
    market: {
      label: "03 · Market opportunity",
      title: "A global operational layer behind insurance.",
      stats: [
        ["850M+", "Insured customers", "Initial target market · US · Europe · Latam"],
        ["450M+", "Annual service events", "Home · Roadside · Medical · Pet · Legal · Concierge & benefits"],
        ["$10B+", "Service execution TAM", "Global insurance assistance services"],
        ["3%", "Weso target", "Market penetration at 10 years"],
        ["13.5M", "Service events / year", "At target penetration"],
        ["$1.35B", "GMV", "Average ticket: USD 100"],
        ["$337M", "Annual Weso revenue", "Assuming an average fee of USD 25 per event"],
      ],
      bridge: "Legacy stack",
      bridgeTo: "Weso infrastructure",
    },
    economics: {
      label: "04 · Changing the economics",
      title: "Why does Weso win now?",
      intro: "From paying for insured members to paying only for services used.",
      from: "Pay for every insured member",
      to: "Pay only for services used",
      changed: "We structurally changed the economics.",
      savingsValue: "45%",
      savings: "savings for insurance companies",
      feeValue: "35%",
      fee: "fee for service — Weso, per service",
      badges: ["One platform", "AI-driven operations", "Usage-based economics"],
    },
    scale: {
      label: "05 · Compounding advantage",
      title: "Weso gets stronger with scale.",
      lead: "Every service improves the infrastructure behind the next one.",
      today: "Today",
      todaySub: "Fragmented. Paid in advance.",
      weso: "With Weso",
      wesoSub: "Unified. Paid for usage.",
      insurer: "Insurance company",
      owner: "Owns the policy & risk",
      paysLegacy: "Pays for coverage / capacity",
      legacyTerms: "Upfront · Per capita · Fixed",
      paysWeso: "Pays only for what is used",
      wesoTerms: "Per service · Transparent · Variable",
      legacyNodes: ["Assistance company", "TPA / operations", "Call center", "Provider networks"],
      infrastructure: "Weso service infrastructure",
      capabilities: ["Smart orchestration", "Quality control", "Real-time tracking", "Data & AI"],
      policyholder: "Policyholder",
      receives: "Receives the service",
    },
    team: {
      label: "Built by insurance + software operations",
      title: "The team behind the layer.",
      members: [
        ["Eduardo Diaz", "COO · Co-founder", "Chile", "/assets/p3-7.png"],
        ["Sebastian Sarovich", "CEO · Founder", "Chile", "/assets/p3-14.png"],
        ["Ricardo Aizenman", "Chairman ICP · Co-founder", "United States", "/assets/p3-4.png"],
        ["Laura Ospina", "AI Manager · Tech Co-founder", "Ecuador", "/assets/p3-5.png"],
        ["Martin Pinto", "CCO · Co-founder", "Uruguay", "/assets/p3-9.png"],
        ["Martin Baumann", "Head of Growth · Co-founder", "Chile", "/assets/p3-12.png"],
      ],
    },
    round: {
      label: "06 · The round",
      title: "Building the operating layer insurance has been missing.",
      terms: [["USD 300K", "Raising"], ["5%", "Equity"], ["Pre-Seed", "Stage"], ["SAFE", "Instrument"]],
      months: "6-month commercial pipeline",
      pipeline: [["4", "in implementation"], ["2", "in decision"], ["182", "insurance companies in pipeline"]],
      uses: [["Technology & AI", "Automate the coordination layer"], ["Insurance integrations", "Connect insurers and service networks"], ["US & EU expansion", "Scale the operating footprint"]],
      closing: "The infrastructure is ready to scale.",
      email: "Email Sebastian",
      emailAddress: "sebastian@weso.ai",
      website: "Visit weso.ai",
      websiteUrl: "https://weso.ai",
    },
  },
  es: {
    nav: { thesis: "Tesis", market: "Mercado", model: "Modelo", team: "Equipo", contact: "Contacto" },
    hero: {
      kicker: "Resumen para inversionistas · Pre-Seed",
      eyebrow: "Plataforma de infraestructura B2B · Experiencia B2B2C · Insurtech",
      titleA: "La capa operativa de IA",
      titleB: "para servicios de seguros.",
      body: "Una infraestructura de coordinación en tiempo real que reemplaza call centers, intermediarios y operadores legacy.",
      explore: "Explorar la tesis",
      signal: "IA nativa · Tiempo real · Pago por uso",
    },
    problem: {
      label: "01 · El problema",
      title: "La capa operativa de los seguros está rota.",
      lead: "El modelo tradicional de asistencia de seguros está fragmentado, es costoso y depende intensamente de la coordinación manual.",
      body: "Weso reemplaza call centers, intermediarios y operadores legacy con una infraestructura de coordinación en tiempo real que reduce costos, mejora la ejecución y convierte la asistencia en un modelo escalable de pago por servicio.",
      marketTitle: "Qué está roto en el mercado actual",
      marketLead: "Detrás de cada póliza existe una infraestructura operativa fragmentada, construida décadas antes de la automatización en tiempo real.",
      cards: [
        ["Incentivos financieros rotos", "El sistema gana más dinero cuando gasta menos en servicio al cliente."],
        ["Dependencia de intermediarios", "Hay demasiadas capas operativas entre la aseguradora y la solución real."],
        ["Pérdida del control del cliente", "Las aseguradoras tercerizan su experiencia de cliente a actores externos."],
        ["Infraestructura obsoleta", "El modelo actual aún depende de procesos manuales y estructuras anteriores a la era de la IA."],
      ],
    },
    solution: {
      label: "02 · La solución",
      title: "Nuestra solución, reinventada.",
      flow: ["Solicitud", "Ingreso por IA", "Match", "Asignación", "Seguimiento", "Resolución", "Datos de vuelta"],
      pillars: [
        ["Una capa operativa de IA", "Weso consolida TPAs, compañías de asistencia, operaciones de despacho y call centers en una sola plataforma de coordinación impulsada por IA."],
        ["Operaciones nativas en IA y tiempo real", "Automatizamos la orquestación del servicio de punta a punta, reduciendo fricción operativa, tiempos de respuesta y costos fijos."],
        ["Economía basada en uso", "A diferencia de los modelos legacy por cápita, Weso opera con una estructura flexible de pago por uso habilitada por automatización y coordinación inteligente."],
      ],
    },
    market: {
      label: "03 · Oportunidad de mercado",
      title: "Una capa operativa global detrás de los seguros.",
      stats: [
        ["850M+", "Clientes asegurados", "Mercado objetivo inicial · EE.UU. · Europa · Latam"],
        ["450M+", "Eventos de servicio anuales", "Hogar · Carretera · Médico · Mascotas · Legal · Concierge y beneficios"],
        ["USD 10B+", "TAM de ejecución de servicios", "Servicios globales de asistencia de seguros"],
        ["3%", "Objetivo de Weso", "Penetración de mercado a 10 años"],
        ["13,5M", "Eventos de servicio / año", "Con la penetración objetivo"],
        ["USD 1,35B", "GMV", "Ticket promedio: USD 100"],
        ["USD 337M", "Ingresos anuales de Weso", "Asumiendo un fee promedio de USD 25 por evento"],
      ],
      bridge: "Stack legacy",
      bridgeTo: "Infraestructura Weso",
    },
    economics: {
      label: "04 · Cambiando la economía",
      title: "¿Por qué Weso gana ahora?",
      intro: "De pagar por cada asegurado a pagar solo por los servicios utilizados.",
      from: "Pagar por cada asegurado",
      to: "Pagar solo por servicios utilizados",
      changed: "Cambiamos estructuralmente la economía.",
      savingsValue: "45%",
      savings: "de ahorro para las aseguradoras",
      feeValue: "35%",
      fee: "fee por servicio — Weso, por servicio",
      badges: ["Una plataforma", "Operaciones impulsadas por IA", "Economía basada en uso"],
    },
    scale: {
      label: "05 · Ventaja acumulativa",
      title: "Weso se fortalece con la escala.",
      lead: "Cada servicio mejora la infraestructura detrás del siguiente.",
      today: "Hoy",
      todaySub: "Fragmentado. Pagado por adelantado.",
      weso: "Con Weso",
      wesoSub: "Unificado. Pagado por uso.",
      insurer: "Aseguradora",
      owner: "Es dueña de la póliza y el riesgo",
      paysLegacy: "Paga por cobertura / capacidad",
      legacyTerms: "Anticipado · Por cápita · Fijo",
      paysWeso: "Paga solo por lo utilizado",
      wesoTerms: "Por servicio · Transparente · Variable",
      legacyNodes: ["Compañía de asistencia", "TPA / operaciones", "Call center", "Redes de proveedores"],
      infrastructure: "Infraestructura de servicios Weso",
      capabilities: ["Orquestación inteligente", "Control de calidad", "Seguimiento en tiempo real", "Datos e IA"],
      policyholder: "Asegurado",
      receives: "Recibe el servicio",
    },
    team: {
      label: "Construida por seguros + operaciones de software",
      title: "El equipo detrás de la capa.",
      members: [
        ["Eduardo Diaz", "COO · Cofundador", "Chile", "/assets/p3-7.png"],
        ["Sebastian Sarovich", "CEO · Fundador", "Chile", "/assets/p3-14.png"],
        ["Ricardo Aizenman", "Chairman ICP · Cofundador", "Estados Unidos", "/assets/p3-4.png"],
        ["Laura Ospina", "AI Manager · Cofundadora Tech", "Ecuador", "/assets/p3-5.png"],
        ["Martin Pinto", "CCO · Cofundador", "Uruguay", "/assets/p3-9.png"],
        ["Martin Baumann", "Head of Growth · Cofundador", "Chile", "/assets/p3-12.png"],
      ],
    },
    round: {
      label: "06 · La ronda",
      title: "Construyendo la capa operativa que le faltaba a los seguros.",
      terms: [["USD 300K", "Capital a levantar"], ["5%", "Equity"], ["Pre-Seed", "Etapa"], ["SAFE", "Instrumento"]],
      months: "Pipeline comercial de 6 meses",
      pipeline: [["4", "en implementación"], ["2", "en decisión"], ["182", "aseguradoras en pipeline"]],
      uses: [["Tecnología e IA", "Automatizar la capa de coordinación"], ["Integraciones con seguros", "Conectar aseguradoras y redes de servicio"], ["Expansión en EE.UU. y UE", "Escalar la presencia operativa"]],
      closing: "La infraestructura está lista para escalar.",
      email: "Escribir a Sebastian",
      emailAddress: "sebastian@weso.ai",
      website: "Visitar weso.ai",
      websiteUrl: "https://weso.ai",
    },
  },
} as const;
