export type Lang = "en" | "es";

export const content = {
  en: {
    nav: { thesis: "Thesis", kpis: "KPIs", market: "Market", model: "Model", team: "Team", contact: "Contact" },
    hero: {
      kicker: "Investor brief · Weso",
      eyebrow: "B2B Infrastructure Platform · B2B2C Experience Layer · Insurtech",
      titleA: "The AI operations layer",
      titleB: "for insurance services.",
      body: "A real-time coordination infrastructure replacing call centers, intermediaries, and legacy operators.",
      explore: "Explore the thesis",
      signal: "AI-native · Real-time · Usage-based",
    },
    problem: {
      label: "01 · The problem",
      title: "The insurance operations layer is broken.",
      lead: "The traditional insurance assistance model is fragmented, expensive, and heavily dependent on manual coordination.",
      body: "Weso replaces call centers, intermediaries, and legacy operators with a real-time coordination infrastructure that reduces costs, improves execution, and transforms assistance into a scalable fee-for-service model.",
      marketTitle: "What’s broken in today’s market",
      marketLead: "Behind every insurance policy exists a fragmented operational infrastructure built decades before real-time automation.",
      cards: [
        ["Broken financial incentives", "The system makes more money when it spends less on customer service."],
        ["Reliance on intermediaries", "There are too many operational layers between the insurer and the actual solution."],
        ["Loss of customer control", "Insurance companies outsource their customer experience to external third parties."],
        ["Outdated infrastructure", "The current model still relies on manual processes and structures designed before the AI era."],
      ],
      calloutLabel: "The risk of customer attention",
      calloutTitle: "The insurer designs the product. The experience is defined in execution.",
      calloutBody: "Traditional assistance protects margin instead of optimizing the insured experience. It wins when it spends less, not when it serves better.",
    },
    solution: {
      label: "02 · The solution",
      title: "Our solution, reimagined.",
      flow: ["Request", "AI Intake", "Match", "Dispatch", "Follow Up", "Resolution", "Data Back"],
      pillars: [
        ["One AI Operations Layer", "Weso consolidates TPAs, assistance companies, dispatch operations, and call centers into a single AI-powered coordination platform."],
        ["AI-native, real-time operations", "We automate service orchestration end-to-end with AI, reducing operational friction, response times, and fixed costs."],
        ["Usage-based economics", "Unlike legacy per-capita models, Weso operates with a flexible pay-per-use structure enabled by automation and intelligent coordination."],
      ],
    },
    core: {
      label: "03 · AI-first by design",
      title: "Technology + AI is our core.",
      lead: "Efficiency comes from technology and automation, not from restricting services.",
      channels: [
        ["Data AI", "Turns every service into operational intelligence."],
        ["Voice AI", "Answers and coordinates in real time."],
        ["Chat AI", "Guides each request from intake to resolution."],
        ["WhatsApp AI", "Meets policyholders in the channel they already use."],
        ["App", "Keeps the service visible, simple, and in control."],
      ],
      human: "+ Human power",
      humanBody: "AI brings speed, consistency, and scale without sacrificing experience or control.",
    },
    performance: {
      label: "03 · NPS & KPIs",
      title: "Operational performance, in numbers.",
      lead: "AI-native coordination is already translating into faster service, greater automation, and a consistently strong customer experience.",
      metrics: [
        { title: "Voice AI + automation", value: "100%", body: "Every request is answered in under 10 seconds." },
        { title: "Faster resolution", value: "8×", body: "Technician assignment and service resolution." },
        { title: "Faster arrival", value: "5×", body: "Time from request to service arrival." },
        { title: "First-contact resolution", value: "98%", body: "Cases resolved during the first interaction." },
        { title: "Autonomous coordination", value: "95%", body: "Completed automatically, without human intervention." },
        { title: "Recorded calls", value: "100%", body: "Every call logged for traceability and quality." },
        { title: "CSAT", value: "4.8/5", body: "Customer satisfaction index.", stars: true },
        { title: "Human handoff", value: "<60s", body: "Transfer time when a person is needed." },
      ],
    },
    market: {
      label: "04 · Projected opportunity",
      title: "From operating volume to Weso revenue.",
      lead: "A focused view of the 72-month projection: scale first, then the value Weso captures.",
      funnel: [
        ["6.58M", "Service cases", "Projected across the operating network"],
        ["USD 754.8M", "Processed service value", "USD 114.76 average ticket"],
        ["USD 217.1M", "Weso revenue", "USD 215.5M in fees + USD 1.54M in licenses"],
      ],
      fee: ["28.6%", "Weighted average fee"],
      basis: "Consolidated scenario · 32 actors · 72 months · Rounded values",
      bridge: "Legacy stack",
      bridgeTo: "Weso infrastructure",
    },
    economics: {
      label: "05 · Changing the economics",
      title: "Why does Weso win now?",
      intro: "From paying for insured members to paying only for services used.",
      from: "Pay for every insured member",
      to: "Pay only for services used",
      changed: "We structurally changed the economics.",
      savingsValue: "45%",
      savings: "savings for insurance companies",
      feeValue: "35%",
      fee: "fee for service — Weso, per service",
      modelNote: "This saving is enabled by Weso’s fee-for-service model. Weso earns a 35% fee on each service delivered.",
      badges: ["One platform", "AI-driven operations", "Usage-based economics"],
    },
    scale: {
      label: "06 · Compounding advantage",
      title: "Weso gets stronger with scale.",
      lead: "Every service improves the infrastructure behind the next one.",
      today: "Today",
      todaySub: "Fragmented. Paid in advance.",
      weso: "With Weso",
      wesoSub: "Unified. Paid for usage.",
      insurer: "Insurance company",
      owner: "Owns the policy & risk",
      paysLegacy: "Pays for coverage / capacity",
      legacyTerms: "Upfront · Per capita · Fixed",
      paysWeso: "Pays only for what is used",
      wesoTerms: "Per service · Transparent · Variable",
      legacyNodes: ["Assistance company", "TPA / operations", "Call center", "Provider networks"],
      infrastructure: "Weso service infrastructure",
      capabilities: ["Smart orchestration", "Quality control", "Real-time tracking", "Data & AI"],
      policyholder: "Policyholder",
      receives: "Receives the service",
    },
    team: {
      label: "Built by insurance + software operations",
      title: "The team behind the layer.",
      members: [
        ["Eduardo Diaz", "COO · Co-founder", "Chile", "/assets/p3-7.png"],
        ["Sebastian Sarovich", "CEO · Founder", "Chile", "/assets/p3-14.png"],
        ["Ricardo Aizenman", "Chairman ICP · Co-founder", "United States", "/assets/p3-4.png"],
        ["Laura Ospina", "AI Manager · Tech Co-founder", "Ecuador", "/assets/p3-5.png"],
        ["Martin Pinto", "CCO · Co-founder", "Uruguay", "/assets/p3-9.png"],
        ["Martin Baumann", "Head of Growth · Co-founder", "Chile", "/assets/p3-12.png"],
      ],
    },
    round: {
      label: "07 · The opportunity",
      title: "Building the operating layer insurance has been missing.",
      months: "6-month commercial pipeline",
      pipeline: [["4", "in implementation"], ["2", "in decision"], ["182", "insurance companies in pipeline"]],
      uses: [["Technology & AI", "Automate the coordination layer"], ["Insurance integrations", "Connect insurers and service networks"], ["US & EU expansion", "Scale the operating footprint"]],
      closing: "The infrastructure is ready to scale.",
      email: "Email Sebastian",
      emailAddress: "sebastian@weso.ai",
      website: "Visit weso.ai",
      websiteUrl: "https://weso.ai",
    },
  },
  es: {
    nav: { thesis: "Tesis", kpis: "KPIs", market: "Mercado", model: "Modelo", team: "Equipo", contact: "Contacto" },
    hero: {
      kicker: "Resumen para inversionistas · Weso",
      eyebrow: "Plataforma de infraestructura B2B · Experiencia B2B2C · Insurtech",
      titleA: "La capa operativa de IA",
      titleB: "para servicios de seguros.",
      body: "Una infraestructura de coordinación en tiempo real que reemplaza call centers, intermediarios y operadores legacy.",
      explore: "Explorar la tesis",
      signal: "IA nativa · Tiempo real · Pago por uso",
    },
    problem: {
      label: "01 · El problema",
      title: "La capa operativa de los seguros está rota.",
      lead: "El modelo tradicional de asistencia de seguros está fragmentado, es costoso y depende intensamente de la coordinación manual.",
      body: "Weso reemplaza call centers, intermediarios y operadores legacy con una infraestructura de coordinación en tiempo real que reduce costos, mejora la ejecución y convierte la asistencia en un modelo escalable de pago por servicio.",
      marketTitle: "Qué está roto en el mercado actual",
      marketLead: "Detrás de cada póliza existe una infraestructura operativa fragmentada, construida décadas antes de la automatización en tiempo real.",
      cards: [
        ["Incentivos financieros rotos", "El sistema gana más dinero cuando gasta menos en servicio al cliente."],
        ["Dependencia de intermediarios", "Hay demasiadas capas operativas entre la aseguradora y la solución real."],
        ["Pérdida del control del cliente", "Las aseguradoras tercerizan su experiencia de cliente a actores externos."],
        ["Infraestructura obsoleta", "El modelo actual aún depende de procesos manuales y estructuras anteriores a la era de la IA."],
      ],
      calloutLabel: "El riesgo de la atención al cliente",
      calloutTitle: "La aseguradora diseña el producto. La experiencia se define en la ejecución.",
      calloutBody: "La asistencia tradicional protege el margen en vez de optimizar la experiencia del asegurado. Gana cuando gasta menos, no cuando atiende mejor.",
    },
    solution: {
      label: "02 · La solución",
      title: "Nuestra solución, reinventada.",
      flow: ["Solicitud", "Ingreso por IA", "Match", "Asignación", "Seguimiento", "Resolución", "Datos de vuelta"],
      pillars: [
        ["Una capa operativa de IA", "Weso consolida TPAs, compañías de asistencia, operaciones de despacho y call centers en una sola plataforma de coordinación impulsada por IA."],
        ["Operaciones nativas en IA y tiempo real", "Automatizamos la orquestación del servicio de punta a punta, reduciendo fricción operativa, tiempos de respuesta y costos fijos."],
        ["Economía basada en uso", "A diferencia de los modelos legacy por cápita, Weso opera con una estructura flexible de pago por uso habilitada por automatización y coordinación inteligente."],
      ],
    },
    core: {
      label: "03 · AI-first by design",
      title: "La tecnología + IA es nuestro core.",
      lead: "La eficiencia proviene de la tecnología y la automatización, no de restringir servicios.",
      channels: [
        ["Data AI", "Convierte cada servicio en inteligencia operativa."],
        ["Voice AI", "Responde y coordina en tiempo real."],
        ["Chat AI", "Guía cada solicitud desde el ingreso hasta la resolución."],
        ["WhatsApp AI", "Acompaña al asegurado en el canal que ya utiliza."],
        ["App", "Mantiene el servicio visible, simple y bajo control."],
      ],
      human: "+ Poder humano",
      humanBody: "La IA aporta velocidad, consistencia y escala sin sacrificar experiencia ni control.",
    },
    performance: {
      label: "03 · NPS & KPIs",
      title: "Desempeño operativo, en números.",
      lead: "La coordinación nativa en IA ya se traduce en un servicio más rápido, mayor automatización y una experiencia de cliente consistentemente sólida.",
      metrics: [
        { title: "Voice AI + automatización", value: "100%", body: "Cada solicitud es atendida en menos de 10 segundos." },
        { title: "Resolución más rápida", value: "8×", body: "Asignación de técnicos y resolución del servicio." },
        { title: "Llegada más rápida", value: "5×", body: "Tiempo desde la solicitud hasta la llegada al servicio." },
        { title: "Resolución al primer contacto", value: "98%", body: "Casos resueltos durante la primera interacción." },
        { title: "Coordinación autónoma", value: "95%", body: "Completada automáticamente, sin intervención humana." },
        { title: "Llamadas grabadas", value: "100%", body: "Cada llamada registrada para trazabilidad y calidad." },
        { title: "CSAT", value: "4,8/5", body: "Índice de satisfacción del cliente.", stars: true },
        { title: "Transferencia a humano", value: "<60s", body: "Tiempo de transferencia cuando se necesita una persona." },
      ],
    },
    market: {
      label: "04 · Oportunidad proyectada",
      title: "Del volumen operativo a los ingresos de Weso.",
      lead: "Una lectura simple de la proyección a 72 meses: primero la escala y luego el valor que captura Weso.",
      funnel: [
        ["6,58M", "Casos de servicio", "Proyectados en toda la red operativa"],
        ["USD 754,8M", "Valor de servicios procesado", "Ticket promedio de USD 114,76"],
        ["USD 217,1M", "Ingresos de Weso", "USD 215,5M en fees + USD 1,54M en licencias"],
      ],
      fee: ["28,6%", "Fee promedio ponderado"],
      basis: "Escenario consolidado · 32 actores · 72 meses · Valores redondeados",
      bridge: "Stack legacy",
      bridgeTo: "Infraestructura Weso",
    },
    economics: {
      label: "05 · Cambiando la economía",
      title: "¿Por qué Weso gana ahora?",
      intro: "De pagar por cada asegurado a pagar solo por los servicios utilizados.",
      from: "Pagar por cada asegurado",
      to: "Pagar solo por servicios utilizados",
      changed: "Cambiamos estructuralmente la economía.",
      savingsValue: "45%",
      savings: "de ahorro para las aseguradoras",
      feeValue: "35%",
      fee: "fee por servicio — Weso, por servicio",
      modelNote: "Este ahorro es posible gracias al modelo fee-for-service de Weso. Weso genera un fee de 35% por cada servicio realizado.",
      badges: ["Una plataforma", "Operaciones impulsadas por IA", "Economía basada en uso"],
    },
    scale: {
      label: "06 · Ventaja acumulativa",
      title: "Weso se fortalece con la escala.",
      lead: "Cada servicio mejora la infraestructura detrás del siguiente.",
      today: "Hoy",
      todaySub: "Fragmentado. Pagado por adelantado.",
      weso: "Con Weso",
      wesoSub: "Unificado. Pagado por uso.",
      insurer: "Aseguradora",
      owner: "Es dueña de la póliza y el riesgo",
      paysLegacy: "Paga por cobertura / capacidad",
      legacyTerms: "Anticipado · Por cápita · Fijo",
      paysWeso: "Paga solo por lo utilizado",
      wesoTerms: "Por servicio · Transparente · Variable",
      legacyNodes: ["Compañía de asistencia", "TPA / operaciones", "Call center", "Redes de proveedores"],
      infrastructure: "Infraestructura de servicios Weso",
      capabilities: ["Orquestación inteligente", "Control de calidad", "Seguimiento en tiempo real", "Datos e IA"],
      policyholder: "Asegurado",
      receives: "Recibe el servicio",
    },
    team: {
      label: "Construida por seguros + operaciones de software",
      title: "El equipo detrás de la capa.",
      members: [
        ["Eduardo Diaz", "COO · Cofundador", "Chile", "/assets/p3-7.png"],
        ["Sebastian Sarovich", "CEO · Fundador", "Chile", "/assets/p3-14.png"],
        ["Ricardo Aizenman", "Chairman ICP · Cofundador", "Estados Unidos", "/assets/p3-4.png"],
        ["Laura Ospina", "AI Manager · Cofundadora Tech", "Ecuador", "/assets/p3-5.png"],
        ["Martin Pinto", "CCO · Cofundador", "Uruguay", "/assets/p3-9.png"],
        ["Martin Baumann", "Head of Growth · Cofundador", "Chile", "/assets/p3-12.png"],
      ],
    },
    round: {
      label: "07 · La oportunidad",
      title: "Construyendo la capa operativa que le faltaba a los seguros.",
      months: "Pipeline comercial de 6 meses",
      pipeline: [["4", "en implementación"], ["2", "en decisión"], ["182", "aseguradoras en pipeline"]],
      uses: [["Tecnología e IA", "Automatizar la capa de coordinación"], ["Integraciones con seguros", "Conectar aseguradoras y redes de servicio"], ["Expansión en EE.UU. y UE", "Escalar la presencia operativa"]],
      closing: "La infraestructura está lista para escalar.",
      email: "Escribir a Sebastian",
      emailAddress: "sebastian@weso.ai",
      website: "Visitar weso.ai",
      websiteUrl: "https://weso.ai",
    },
  },
} as const;
